GET http://localhost:1907/products
###
POST http://localhost:1907/products
Content-Type: application/json

{
    "name":"bmw",
    "price":2010
}
###
GET http://localhost:1907/products/647cf45b82f9f8cf7e2b4806
###
PATCH http://localhost:1907/products/647bb7d4d859771bdedefd07
Content-Type: application/json

{
    "name":"big-ferrari",
    "price":1500
}
###
DELETE  http://localhost:1907/products/647cf45b82f9f8cf7e2b4806

###
GET http://localhost:1907/prod

